self.addEventListener('install',e=>{
  self.skipWaiting();
  e.waitUntil(
    caches.open('v1').then(c=>c.addAll(['./']))
  );
});
self.addEventListener('fetch',e=>{
  e.respondWith(
    caches.match(e.request).then(r=>r||fetch(e.request))
  );
});
